#coding:utf-8
# 2014-12-18
# build by qianqians
# deletenonespacelstrip

def deleteNoneSpacelstrip(_str:str):
    while(_str.lstrip('\r') is not _str):_str = _str.lstrip('\r')
    while(_str.lstrip('\n') is not _str):_str = _str.lstrip('\n')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\t')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\r\n')
    while(_str.lstrip('\0') is not _str):_str = _str.lstrip('\0')
    while(_str.lstrip('\r') is not _str):_str = _str.lstrip('\r')
    while(_str.lstrip('\n') is not _str):_str = _str.lstrip('\n')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\t')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\r\n')
    while(_str.lstrip('\0') is not _str):_str = _str.lstrip('\0')
    while(_str.lstrip('\r') is not _str):_str = _str.lstrip('\r')
    while(_str.lstrip('\n') is not _str):_str = _str.lstrip('\n')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\t')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\r\n')
    while(_str.lstrip('\0') is not _str):_str = _str.lstrip('\0')
    while(_str.lstrip('\r') is not _str):_str = _str.lstrip('\r')
    while(_str.lstrip('\n') is not _str):_str = _str.lstrip('\n')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\t')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\r\n')
    while(_str.lstrip('\0') is not _str):_str = _str.lstrip('\0')
    while(_str.lstrip('\r') is not _str):_str = _str.lstrip('\r')
    while(_str.lstrip('\n') is not _str):_str = _str.lstrip('\n')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\t')
    while(_str.lstrip('\t') is not _str):_str = _str.lstrip('\r\n')
    while(_str.lstrip('\0') is not _str):_str = _str.lstrip('\0')
    while(_str.lstrip('	') is not _str):_str = _str.lstrip('	')
    while(_str.lstrip(' ') is not _str):_str = _str.lstrip(' ')
    while(_str.lstrip('	') is not _str):_str = _str.lstrip('	')
    while(_str.rstrip('\r') is not _str):_str = _str.rstrip('\r')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\n')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\r\n')
    while(_str.rstrip('\t') is not _str):_str = _str.rstrip('\t')
    while(_str.rstrip('\0') is not _str):_str = _str.rstrip('\0')
    while(_str.rstrip('\r') is not _str):_str = _str.rstrip('\r')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\n')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\r\n')
    while(_str.rstrip('\t') is not _str):_str = _str.rstrip('\t')
    while(_str.rstrip('\0') is not _str):_str = _str.rstrip('\0')
    while(_str.rstrip('\r') is not _str):_str = _str.rstrip('\r')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\n')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\r\n')
    while(_str.rstrip('\t') is not _str):_str = _str.rstrip('\t')
    while(_str.rstrip('\0') is not _str):_str = _str.rstrip('\0')
    while(_str.rstrip('\r') is not _str):_str = _str.rstrip('\r')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\n')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\r\n')
    while(_str.rstrip('\t') is not _str):_str = _str.rstrip('\t')
    while(_str.rstrip('\0') is not _str):_str = _str.rstrip('\0')
    while(_str.rstrip('\r') is not _str):_str = _str.rstrip('\r')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\n')
    while(_str.rstrip('\n') is not _str):_str = _str.rstrip('\r\n')
    while(_str.rstrip('\t') is not _str):_str = _str.rstrip('\t')
    while(_str.rstrip('\0') is not _str):_str = _str.rstrip('\0')
    while(_str.rstrip('	') is not _str):_str = _str.rstrip('	')
    while(_str.rstrip(' ') is not _str):_str = _str.rstrip(' ')
    while(_str.rstrip('	') is not _str):_str = _str.rstrip('	')
    return _str