// Autogenerated by Thrift Compiler (0.18.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

use crate::common;

//
// CreateRemoteEntity
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CreateRemoteEntity {
  pub entity_id: Option<String>,
  pub entity_type: Option<String>,
  pub is_main: Option<bool>,
  pub argvs: Option<Vec<u8>>,
}

impl CreateRemoteEntity {
  pub fn new<F1, F2, F3, F4>(entity_id: F1, entity_type: F2, is_main: F3, argvs: F4) -> CreateRemoteEntity where F1: Into<Option<String>>, F2: Into<Option<String>>, F3: Into<Option<bool>>, F4: Into<Option<Vec<u8>>> {
    CreateRemoteEntity {
      entity_id: entity_id.into(),
      entity_type: entity_type.into(),
      is_main: is_main.into(),
      argvs: argvs.into(),
    }
  }
}

impl TSerializable for CreateRemoteEntity {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CreateRemoteEntity> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    let mut f_2: Option<String> = Some("".to_owned());
    let mut f_3: Option<bool> = Some(false);
    let mut f_4: Option<Vec<u8>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_bool()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_bytes()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CreateRemoteEntity {
      entity_id: f_1,
      entity_type: f_2,
      is_main: f_3,
      argvs: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("create_remote_entity");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.entity_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.entity_type {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_type", TType::String, 2))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.is_main {
      o_prot.write_field_begin(&TFieldIdentifier::new("is_main", TType::Bool, 3))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.argvs {
      o_prot.write_field_begin(&TFieldIdentifier::new("argvs", TType::String, 4))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// DeleteRemoteEntity
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DeleteRemoteEntity {
  pub entity_id: Option<String>,
}

impl DeleteRemoteEntity {
  pub fn new<F1>(entity_id: F1) -> DeleteRemoteEntity where F1: Into<Option<String>> {
    DeleteRemoteEntity {
      entity_id: entity_id.into(),
    }
  }
}

impl TSerializable for DeleteRemoteEntity {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<DeleteRemoteEntity> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = DeleteRemoteEntity {
      entity_id: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("delete_remote_entity");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.entity_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// RefreshEntity
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RefreshEntity {
  pub entity_id: Option<String>,
  pub entity_type: Option<String>,
  pub is_main: Option<bool>,
  pub argvs: Option<Vec<u8>>,
}

impl RefreshEntity {
  pub fn new<F1, F2, F3, F4>(entity_id: F1, entity_type: F2, is_main: F3, argvs: F4) -> RefreshEntity where F1: Into<Option<String>>, F2: Into<Option<String>>, F3: Into<Option<bool>>, F4: Into<Option<Vec<u8>>> {
    RefreshEntity {
      entity_id: entity_id.into(),
      entity_type: entity_type.into(),
      is_main: is_main.into(),
      argvs: argvs.into(),
    }
  }
}

impl TSerializable for RefreshEntity {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<RefreshEntity> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    let mut f_2: Option<String> = Some("".to_owned());
    let mut f_3: Option<bool> = Some(false);
    let mut f_4: Option<Vec<u8>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_bool()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_bytes()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = RefreshEntity {
      entity_id: f_1,
      entity_type: f_2,
      is_main: f_3,
      argvs: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("refresh_entity");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.entity_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.entity_type {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_type", TType::String, 2))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.is_main {
      o_prot.write_field_begin(&TFieldIdentifier::new("is_main", TType::Bool, 3))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.argvs {
      o_prot.write_field_begin(&TFieldIdentifier::new("argvs", TType::String, 4))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TransferComplete
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TransferComplete {
}

impl TransferComplete {
  pub fn new() -> TransferComplete {
    TransferComplete {}
  }
}

impl TSerializable for TransferComplete {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TransferComplete> {
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      i_prot.skip(field_ident.field_type)?;
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TransferComplete {};
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("transfer_complete");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// KickOff
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct KickOff {
  pub prompt_info: Option<String>,
}

impl KickOff {
  pub fn new<F1>(prompt_info: F1) -> KickOff where F1: Into<Option<String>> {
    KickOff {
      prompt_info: prompt_info.into(),
    }
  }
}

impl TSerializable for KickOff {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<KickOff> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = KickOff {
      prompt_info: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("kick_off");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.prompt_info {
      o_prot.write_field_begin(&TFieldIdentifier::new("prompt_info", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// NtfConnId
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct NtfConnId {
  pub conn_id: Option<String>,
}

impl NtfConnId {
  pub fn new<F1>(conn_id: F1) -> NtfConnId where F1: Into<Option<String>> {
    NtfConnId {
      conn_id: conn_id.into(),
    }
  }
}

impl TSerializable for NtfConnId {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<NtfConnId> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = NtfConnId {
      conn_id: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("ntf_conn_id");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.conn_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("conn_id", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// CallRpc
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CallRpc {
  pub hub_name: Option<String>,
  pub entity_id: Option<String>,
  pub msg_cb_id: Option<i64>,
  pub message: Option<common::Msg>,
}

impl CallRpc {
  pub fn new<F1, F2, F3, F4>(hub_name: F1, entity_id: F2, msg_cb_id: F3, message: F4) -> CallRpc where F1: Into<Option<String>>, F2: Into<Option<String>>, F3: Into<Option<i64>>, F4: Into<Option<common::Msg>> {
    CallRpc {
      hub_name: hub_name.into(),
      entity_id: entity_id.into(),
      msg_cb_id: msg_cb_id.into(),
      message: message.into(),
    }
  }
}

impl TSerializable for CallRpc {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CallRpc> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    let mut f_2: Option<String> = Some("".to_owned());
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<common::Msg> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = common::Msg::read_from_in_protocol(i_prot)?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CallRpc {
      hub_name: f_1,
      entity_id: f_2,
      msg_cb_id: f_3,
      message: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("call_rpc");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.hub_name {
      o_prot.write_field_begin(&TFieldIdentifier::new("hub_name", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.entity_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::String, 2))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.msg_cb_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("msg_cb_id", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.message {
      o_prot.write_field_begin(&TFieldIdentifier::new("message", TType::Struct, 4))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// CallRsp
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CallRsp {
  pub rsp: Option<common::RpcRsp>,
}

impl CallRsp {
  pub fn new<F1>(rsp: F1) -> CallRsp where F1: Into<Option<common::RpcRsp>> {
    CallRsp {
      rsp: rsp.into(),
    }
  }
}

impl TSerializable for CallRsp {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CallRsp> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<common::RpcRsp> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = common::RpcRsp::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CallRsp {
      rsp: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("call_rsp");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.rsp {
      o_prot.write_field_begin(&TFieldIdentifier::new("rsp", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// CallErr
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CallErr {
  pub err: Option<common::RpcErr>,
}

impl CallErr {
  pub fn new<F1>(err: F1) -> CallErr where F1: Into<Option<common::RpcErr>> {
    CallErr {
      err: err.into(),
    }
  }
}

impl TSerializable for CallErr {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CallErr> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<common::RpcErr> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = common::RpcErr::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CallErr {
      err: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("call_err");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.err {
      o_prot.write_field_begin(&TFieldIdentifier::new("err", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// CallNtf
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CallNtf {
  pub hub_name: Option<String>,
  pub entity_id: Option<String>,
  pub message: Option<common::Msg>,
}

impl CallNtf {
  pub fn new<F1, F2, F3>(hub_name: F1, entity_id: F2, message: F3) -> CallNtf where F1: Into<Option<String>>, F2: Into<Option<String>>, F3: Into<Option<common::Msg>> {
    CallNtf {
      hub_name: hub_name.into(),
      entity_id: entity_id.into(),
      message: message.into(),
    }
  }
}

impl TSerializable for CallNtf {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CallNtf> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    let mut f_2: Option<String> = Some("".to_owned());
    let mut f_3: Option<common::Msg> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = common::Msg::read_from_in_protocol(i_prot)?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CallNtf {
      hub_name: f_1,
      entity_id: f_2,
      message: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("call_ntf");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.hub_name {
      o_prot.write_field_begin(&TFieldIdentifier::new("hub_name", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.entity_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::String, 2))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.message {
      o_prot.write_field_begin(&TFieldIdentifier::new("message", TType::Struct, 3))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// CallGlobal
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CallGlobal {
  pub hub_name: Option<String>,
  pub message: Option<common::Msg>,
}

impl CallGlobal {
  pub fn new<F1, F2>(hub_name: F1, message: F2) -> CallGlobal where F1: Into<Option<String>>, F2: Into<Option<common::Msg>> {
    CallGlobal {
      hub_name: hub_name.into(),
      message: message.into(),
    }
  }
}

impl TSerializable for CallGlobal {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<CallGlobal> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = Some("".to_owned());
    let mut f_2: Option<common::Msg> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = common::Msg::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = CallGlobal {
      hub_name: f_1,
      message: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("call_global");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.hub_name {
      o_prot.write_field_begin(&TFieldIdentifier::new("hub_name", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.message {
      o_prot.write_field_begin(&TFieldIdentifier::new("message", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// GateCallHeartbeats
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct GateCallHeartbeats {
  pub timetmp: Option<i64>,
}

impl GateCallHeartbeats {
  pub fn new<F1>(timetmp: F1) -> GateCallHeartbeats where F1: Into<Option<i64>> {
    GateCallHeartbeats {
      timetmp: timetmp.into(),
    }
  }
}

impl TSerializable for GateCallHeartbeats {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<GateCallHeartbeats> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = GateCallHeartbeats {
      timetmp: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("gate_call_heartbeats");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.timetmp {
      o_prot.write_field_begin(&TFieldIdentifier::new("timetmp", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// ClientService
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ClientService {
  CreateRemoteEntity(CreateRemoteEntity),
  DeleteRemoteEntity(DeleteRemoteEntity),
  RefreshEntity(RefreshEntity),
  ConnId(NtfConnId),
  KickOff(KickOff),
  TransferComplete(TransferComplete),
  CallRpc(CallRpc),
  CallRsp(CallRsp),
  CallErr(CallErr),
  CallNtf(CallNtf),
  CallGlobal(CallGlobal),
  Heartbeats(GateCallHeartbeats),
}

impl TSerializable for ClientService {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<ClientService> {
    let mut ret: Option<ClientService> = None;
    let mut received_field_count = 0;
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = CreateRemoteEntity::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CreateRemoteEntity(val));
          }
          received_field_count += 1;
        },
        2 => {
          let val = DeleteRemoteEntity::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::DeleteRemoteEntity(val));
          }
          received_field_count += 1;
        },
        3 => {
          let val = RefreshEntity::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::RefreshEntity(val));
          }
          received_field_count += 1;
        },
        4 => {
          let val = NtfConnId::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::ConnId(val));
          }
          received_field_count += 1;
        },
        5 => {
          let val = KickOff::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::KickOff(val));
          }
          received_field_count += 1;
        },
        6 => {
          let val = TransferComplete::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::TransferComplete(val));
          }
          received_field_count += 1;
        },
        7 => {
          let val = CallRpc::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CallRpc(val));
          }
          received_field_count += 1;
        },
        8 => {
          let val = CallRsp::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CallRsp(val));
          }
          received_field_count += 1;
        },
        9 => {
          let val = CallErr::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CallErr(val));
          }
          received_field_count += 1;
        },
        10 => {
          let val = CallNtf::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CallNtf(val));
          }
          received_field_count += 1;
        },
        11 => {
          let val = CallGlobal::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::CallGlobal(val));
          }
          received_field_count += 1;
        },
        12 => {
          let val = GateCallHeartbeats::read_from_in_protocol(i_prot)?;
          if ret.is_none() {
            ret = Some(ClientService::Heartbeats(val));
          }
          received_field_count += 1;
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
          received_field_count += 1;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    if received_field_count == 0 {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(
            ProtocolErrorKind::InvalidData,
            "received empty union from remote ClientService"
          )
        )
      )
    } else if received_field_count > 1 {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(
            ProtocolErrorKind::InvalidData,
            "received multiple fields for union from remote ClientService"
          )
        )
      )
    } else {
      Ok(ret.expect("return value should have been constructed"))
    }
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("client_service");
    o_prot.write_struct_begin(&struct_ident)?;
    match *self {
      ClientService::CreateRemoteEntity(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("create_remote_entity", TType::Struct, 1))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::DeleteRemoteEntity(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("delete_remote_entity", TType::Struct, 2))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::RefreshEntity(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("refresh_entity", TType::Struct, 3))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::ConnId(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("conn_id", TType::Struct, 4))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::KickOff(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("kick_off", TType::Struct, 5))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::TransferComplete(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("transfer_complete", TType::Struct, 6))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::CallRpc(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("call_rpc", TType::Struct, 7))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::CallRsp(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("call_rsp", TType::Struct, 8))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::CallErr(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("call_err", TType::Struct, 9))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::CallNtf(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("call_ntf", TType::Struct, 10))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::CallGlobal(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("call_global", TType::Struct, 11))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      ClientService::Heartbeats(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("heartbeats", TType::Struct, 12))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

