/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Iclient_request_hub_reconnectArgs {
    account_id?: string;
    token?: string;
}
export class client_request_hub_reconnect {
    public account_id?: string;
    public token?: string;
    constructor(args?: Iclient_request_hub_reconnectArgs) {
        if (args != null && args.account_id != null) {
            this.account_id = args.account_id;
        }
        if (args != null && args.token != null) {
            this.token = args.token;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("client_request_hub_reconnect");
        if (this.account_id != null) {
            output.writeFieldBegin("account_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.account_id);
            output.writeFieldEnd();
        }
        if (this.token != null) {
            output.writeFieldBegin("token", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.token);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): client_request_hub_reconnect {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.account_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.token = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new client_request_hub_reconnect(_args);
    }
}
