/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Iclient_request_hub_serviceArgs {
    service_name?: string;
}
export class client_request_hub_service {
    public service_name?: string;
    constructor(args?: Iclient_request_hub_serviceArgs) {
        if (args != null && args.service_name != null) {
            this.service_name = args.service_name;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("client_request_hub_service");
        if (this.service_name != null) {
            output.writeFieldBegin("service_name", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.service_name);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): client_request_hub_service {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.service_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new client_request_hub_service(_args);
    }
}
