/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Ihub_call_client_create_remote_entityArgs {
    conn_id?: Array<string>;
    main_conn_id?: string;
    entity_id?: string;
    entity_type?: string;
    argvs?: Buffer;
}
export class hub_call_client_create_remote_entity {
    public conn_id?: Array<string>;
    public main_conn_id?: string;
    public entity_id?: string;
    public entity_type?: string;
    public argvs?: Buffer;
    constructor(args?: Ihub_call_client_create_remote_entityArgs) {
        if (args != null && args.conn_id != null) {
            this.conn_id = args.conn_id;
        }
        if (args != null && args.main_conn_id != null) {
            this.main_conn_id = args.main_conn_id;
        }
        if (args != null && args.entity_id != null) {
            this.entity_id = args.entity_id;
        }
        if (args != null && args.entity_type != null) {
            this.entity_type = args.entity_type;
        }
        if (args != null && args.argvs != null) {
            this.argvs = args.argvs;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("hub_call_client_create_remote_entity");
        if (this.conn_id != null) {
            output.writeFieldBegin("conn_id", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.conn_id.length);
            this.conn_id.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.main_conn_id != null) {
            output.writeFieldBegin("main_conn_id", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.main_conn_id);
            output.writeFieldEnd();
        }
        if (this.entity_id != null) {
            output.writeFieldBegin("entity_id", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.entity_id);
            output.writeFieldEnd();
        }
        if (this.entity_type != null) {
            output.writeFieldBegin("entity_type", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.entity_type);
            output.writeFieldEnd();
        }
        if (this.argvs != null) {
            output.writeFieldBegin("argvs", thrift.Thrift.Type.STRING, 5);
            output.writeBinary(this.argvs);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): hub_call_client_create_remote_entity {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<string> = new Array<string>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: string = input.readString();
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.conn_id = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.main_conn_id = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.entity_id = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.entity_type = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: Buffer = input.readBinary();
                        _args.argvs = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new hub_call_client_create_remote_entity(_args);
    }
}
