/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Ihub_call_kick_off_clientArgs {
    conn_id?: string;
    prompt_info?: string;
}
export class hub_call_kick_off_client {
    public conn_id?: string;
    public prompt_info?: string;
    constructor(args?: Ihub_call_kick_off_clientArgs) {
        if (args != null && args.conn_id != null) {
            this.conn_id = args.conn_id;
        }
        if (args != null && args.prompt_info != null) {
            this.prompt_info = args.prompt_info;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("hub_call_kick_off_client");
        if (this.conn_id != null) {
            output.writeFieldBegin("conn_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.conn_id);
            output.writeFieldEnd();
        }
        if (this.prompt_info != null) {
            output.writeFieldBegin("prompt_info", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.prompt_info);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): hub_call_kick_off_client {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.conn_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.prompt_info = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new hub_call_kick_off_client(_args);
    }
}
