/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Ihub_call_transfer_clientArgs {
    conn_id?: string;
    prompt_info?: string;
    new_gate?: string;
    new_conn_id?: string;
    is_reconnect?: boolean;
}
export class hub_call_transfer_client {
    public conn_id?: string;
    public prompt_info?: string;
    public new_gate?: string;
    public new_conn_id?: string;
    public is_reconnect?: boolean;
    constructor(args?: Ihub_call_transfer_clientArgs) {
        if (args != null && args.conn_id != null) {
            this.conn_id = args.conn_id;
        }
        if (args != null && args.prompt_info != null) {
            this.prompt_info = args.prompt_info;
        }
        if (args != null && args.new_gate != null) {
            this.new_gate = args.new_gate;
        }
        if (args != null && args.new_conn_id != null) {
            this.new_conn_id = args.new_conn_id;
        }
        if (args != null && args.is_reconnect != null) {
            this.is_reconnect = args.is_reconnect;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("hub_call_transfer_client");
        if (this.conn_id != null) {
            output.writeFieldBegin("conn_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.conn_id);
            output.writeFieldEnd();
        }
        if (this.prompt_info != null) {
            output.writeFieldBegin("prompt_info", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.prompt_info);
            output.writeFieldEnd();
        }
        if (this.new_gate != null) {
            output.writeFieldBegin("new_gate", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.new_gate);
            output.writeFieldEnd();
        }
        if (this.new_conn_id != null) {
            output.writeFieldBegin("new_conn_id", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.new_conn_id);
            output.writeFieldEnd();
        }
        if (this.is_reconnect != null) {
            output.writeFieldBegin("is_reconnect", thrift.Thrift.Type.BOOL, 5);
            output.writeBool(this.is_reconnect);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): hub_call_transfer_client {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.conn_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.prompt_info = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.new_gate = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.new_conn_id = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_5: boolean = input.readBool();
                        _args.is_reconnect = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new hub_call_transfer_client(_args);
    }
}
