/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as __ROOT_NAMESPACE__ from "./";
export interface Icall_rpcArgs {
    hub_name?: string;
    entity_id?: string;
    msg_cb_id?: number | Int64;
    message?: __ROOT_NAMESPACE__.msg;
}
export class call_rpc {
    public hub_name?: string;
    public entity_id?: string;
    public msg_cb_id?: Int64;
    public message?: __ROOT_NAMESPACE__.msg;
    constructor(args?: Icall_rpcArgs) {
        if (args != null && args.hub_name != null) {
            this.hub_name = args.hub_name;
        }
        if (args != null && args.entity_id != null) {
            this.entity_id = args.entity_id;
        }
        if (args != null && args.msg_cb_id != null) {
            if (typeof args.msg_cb_id === "number") {
                this.msg_cb_id = new Int64(args.msg_cb_id);
            }
            else {
                this.msg_cb_id = args.msg_cb_id;
            }
        }
        if (args != null && args.message != null) {
            this.message = args.message;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("call_rpc");
        if (this.hub_name != null) {
            output.writeFieldBegin("hub_name", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.hub_name);
            output.writeFieldEnd();
        }
        if (this.entity_id != null) {
            output.writeFieldBegin("entity_id", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.entity_id);
            output.writeFieldEnd();
        }
        if (this.msg_cb_id != null) {
            output.writeFieldBegin("msg_cb_id", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.msg_cb_id);
            output.writeFieldEnd();
        }
        if (this.message != null) {
            output.writeFieldBegin("message", thrift.Thrift.Type.STRUCT, 4);
            this.message.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): call_rpc {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.hub_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.entity_id = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.msg_cb_id = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: __ROOT_NAMESPACE__.msg = __ROOT_NAMESPACE__.msg.read(input);
                        _args.message = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new call_rpc(_args);
    }
}
