/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as __ROOT_NAMESPACE__ from "./";
export interface Icall_rspArgs {
    rsp?: __ROOT_NAMESPACE__.rpc_rsp;
}
export class call_rsp {
    public rsp?: __ROOT_NAMESPACE__.rpc_rsp;
    constructor(args?: Icall_rspArgs) {
        if (args != null && args.rsp != null) {
            this.rsp = args.rsp;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("call_rsp");
        if (this.rsp != null) {
            output.writeFieldBegin("rsp", thrift.Thrift.Type.STRUCT, 1);
            this.rsp.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): call_rsp {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: __ROOT_NAMESPACE__.rpc_rsp = __ROOT_NAMESPACE__.rpc_rsp.read(input);
                        _args.rsp = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new call_rsp(_args);
    }
}
