/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as __ROOT_NAMESPACE__ from "./";
export interface Iclient_call_hub_errArgs {
    err?: __ROOT_NAMESPACE__.rpc_err;
}
export class client_call_hub_err {
    public err?: __ROOT_NAMESPACE__.rpc_err;
    constructor(args?: Iclient_call_hub_errArgs) {
        if (args != null && args.err != null) {
            this.err = args.err;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("client_call_hub_err");
        if (this.err != null) {
            output.writeFieldBegin("err", thrift.Thrift.Type.STRUCT, 1);
            this.err.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): client_call_hub_err {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: __ROOT_NAMESPACE__.rpc_err = __ROOT_NAMESPACE__.rpc_err.read(input);
                        _args.err = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new client_call_hub_err(_args);
    }
}
