/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface Igate_call_heartbeatsArgs {
    timetmp?: number | Int64;
}
export class gate_call_heartbeats {
    public timetmp?: Int64;
    constructor(args?: Igate_call_heartbeatsArgs) {
        if (args != null && args.timetmp != null) {
            if (typeof args.timetmp === "number") {
                this.timetmp = new Int64(args.timetmp);
            }
            else {
                this.timetmp = args.timetmp;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("gate_call_heartbeats");
        if (this.timetmp != null) {
            output.writeFieldBegin("timetmp", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.timetmp);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): gate_call_heartbeats {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.timetmp = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new gate_call_heartbeats(_args);
    }
}
