/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Ikick_offArgs {
    prompt_info?: string;
}
export class kick_off {
    public prompt_info?: string;
    constructor(args?: Ikick_offArgs) {
        if (args != null && args.prompt_info != null) {
            this.prompt_info = args.prompt_info;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("kick_off");
        if (this.prompt_info != null) {
            output.writeFieldBegin("prompt_info", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.prompt_info);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): kick_off {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.prompt_info = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new kick_off(_args);
    }
}
