/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ImsgArgs {
    method?: string;
    argvs?: Buffer;
}
export class msg {
    public method?: string;
    public argvs?: Buffer;
    constructor(args?: ImsgArgs) {
        if (args != null && args.method != null) {
            this.method = args.method;
        }
        if (args != null && args.argvs != null) {
            this.argvs = args.argvs;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("msg");
        if (this.method != null) {
            output.writeFieldBegin("method", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.method);
            output.writeFieldEnd();
        }
        if (this.argvs != null) {
            output.writeFieldBegin("argvs", thrift.Thrift.Type.STRING, 2);
            output.writeBinary(this.argvs);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): msg {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.method = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: Buffer = input.readBinary();
                        _args.argvs = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new msg(_args);
    }
}
