/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface Ireg_hubArgs {
    hub_name?: string;
}
export class reg_hub {
    public hub_name?: string;
    constructor(args?: Ireg_hubArgs) {
        if (args != null && args.hub_name != null) {
            this.hub_name = args.hub_name;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("reg_hub");
        if (this.hub_name != null) {
            output.writeFieldBegin("hub_name", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.hub_name);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): reg_hub {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.hub_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new reg_hub(_args);
    }
}
