//! WGSL code generation — produces valid, compilable WGSL from composed shader descriptions.

use crate::core::*;
use crate::stream::*;
use std::collections::HashMap;

// ─── Composed Shader ─────────────────────────────────────────────────────────

/// A fully composed shader description ready for WGSL generation.
#[derive(Debug, Clone)]
pub struct ComposedShader {
    pub name: String,
    pub streams: StreamRouter,
    pub bindings: Vec<ShaderBinding>,
    pub structs: Vec<StructDef>,
    pub functions: Vec<FunctionDef>,
    pub vertex_entry: Option<EntryPointDef>,
    pub fragment_entry: Option<EntryPointDef>,
    pub compute_entry: Option<ComputeEntryPointDef>,
    pub constants: Vec<ConstantDef>,
    pub global_vars: Vec<GlobalVarDef>,
}

// ─── Entry Point Types ───────────────────────────────────────────────────────

/// Entry point definition for vertex/fragment stages.
#[derive(Debug, Clone)]
pub struct EntryPointDef {
    pub name: String,
    pub body: WgslFragment,
    /// Additional local variables declared inside the function: (name, type, optional init).
    pub local_vars: Vec<(String, WgslType, Option<String>)>,
}

/// Compute shader entry point.
#[derive(Debug, Clone)]
pub struct ComputeEntryPointDef {
    pub name: String,
    pub workgroup_size: [u32; 3],
    pub body: WgslFragment,
    pub local_vars: Vec<(String, WgslType, Option<String>)>,
}

/// Pipeline-overridable constant.
#[derive(Debug, Clone)]
pub struct ConstantDef {
    pub name: String,
    pub ty: WgslType,
    pub id: u32,
    pub default_value: Option<String>,
}

/// Global variable (non-binding, e.g. `var<private>`).
#[derive(Debug, Clone)]
pub struct GlobalVarDef {
    pub name: String,
    pub ty: WgslType,
    pub address_space: AddressSpace,
    pub init: Option<String>,
}

/// Address space for global variables.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AddressSpace {
    Private,
    Workgroup,
}

impl AddressSpace {
    /// WGSL keyword for this address space.
    pub fn to_wgsl(&self) -> &'static str {
        match self {
            Self::Private => "private",
            Self::Workgroup => "workgroup",
        }
    }
}

// ─── WGSL Generator ──────────────────────────────────────────────────────────

/// The main WGSL code generator.
///
/// Takes a [`ComposedShader`] and produces a complete, valid WGSL source string.
pub struct WgslGenerator;

impl WgslGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate complete WGSL source from a composed shader.
    ///
    /// Output order:
    /// 1. Header comment
    /// 2. Pipeline-overridable constants
    /// 3. Struct definitions
    /// 4. Global variables (`var<private>`, `var<workgroup>`)
    /// 5. Binding declarations (`@group @binding`)
    /// 6. Helper/utility functions (non-entry-point)
    /// 7. Vertex entry point
    /// 8. Fragment entry point
    /// 9. Compute entry point
    pub fn generate(&self, shader: &ComposedShader) -> ShaderResult<String> {
        let mut parts: Vec<String> = Vec::new();

        // 1. Header
        parts.push(format!(
            "// Generated by shader_framework — {}\n",
            shader.name
        ));

        // 2. Constants
        let constants = self.generate_constants(&shader.constants);
        if !constants.is_empty() {
            parts.push(constants);
        }

        // 3. Structs
        let structs = self.generate_structs(&shader.structs);
        if !structs.is_empty() {
            parts.push(structs);
        }

        // 4. Global variables
        let globals = self.generate_global_vars(&shader.global_vars);
        if !globals.is_empty() {
            parts.push(globals);
        }

        // 5. Bindings
        let bindings = self.generate_bindings(&shader.bindings)?;
        if !bindings.is_empty() {
            parts.push(bindings);
        }

        // 6. Helper functions
        let functions = self.generate_functions(&shader.functions);
        if !functions.is_empty() {
            parts.push(functions);
        }

        // 7. Vertex entry point
        if let Some(ref entry) = shader.vertex_entry {
            let vs = self.generate_vertex_entry(&shader.streams, entry, &shader.bindings)?;
            parts.push(vs);
        }

        // 8. Fragment entry point
        if let Some(ref entry) = shader.fragment_entry {
            let fs = self.generate_fragment_entry(&shader.streams, entry, &shader.bindings)?;
            parts.push(fs);
        }

        // 9. Compute entry point
        if let Some(ref entry) = shader.compute_entry {
            let cs = self.generate_compute_entry(entry, &shader.bindings)?;
            parts.push(cs);
        }

        Ok(parts.join("\n"))
    }

    /// Generate only the struct definitions section.
    pub fn generate_structs(&self, structs: &[StructDef]) -> String {
        structs
            .iter()
            .map(|s| s.to_wgsl())
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Generate binding declarations, sorted by (group, binding).
    ///
    /// Detects conflicts (same group:binding used by different names).
    pub fn generate_bindings(&self, bindings: &[ShaderBinding]) -> ShaderResult<String> {
        // Check for conflicts.
        let mut seen: HashMap<(u32, u32), &str> = HashMap::new();
        for b in bindings {
            if let Some(existing) = seen.get(&(b.group, b.binding)) {
                if *existing != b.name.as_str() {
                    return Err(ShaderError::BindingConflict {
                        group: b.group,
                        binding: b.binding,
                        existing: existing.to_string(),
                        new: b.name.clone(),
                    });
                }
            } else {
                seen.insert((b.group, b.binding), &b.name);
            }
        }

        // Sort by (group, binding).
        let mut sorted: Vec<&ShaderBinding> = bindings.iter().collect();
        sorted.sort_by_key(|b| (b.group, b.binding));

        let lines: Vec<String> = sorted
            .iter()
            .map(|b| {
                let wgsl = b.to_wgsl();
                // Buffer bindings from to_wgsl() lack a trailing semicolon.
                if wgsl.ends_with(';') {
                    wgsl
                } else {
                    format!("{};", wgsl)
                }
            })
            .collect();

        Ok(lines.join("\n"))
    }

    /// Generate all helper functions (non-entry-point).
    pub fn generate_functions(&self, functions: &[FunctionDef]) -> String {
        functions
            .iter()
            .map(|f| f.to_wgsl())
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Generate pipeline-overridable constants.
    pub fn generate_constants(&self, constants: &[ConstantDef]) -> String {
        constants
            .iter()
            .map(|c| {
                let default = match &c.default_value {
                    Some(v) => format!(" = {}", v),
                    None => String::new(),
                };
                format!(
                    "override @id({}) {}: {}{};",
                    c.id,
                    c.name,
                    c.ty.to_wgsl(),
                    default
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Generate the vertex entry point function with proper I/O structs.
    ///
    /// 1. Generates `VertexInput` struct from router (VS-only + VS-to-FS streams as `@location` inputs).
    /// 2. Generates `VertexOutput` struct (`@builtin(position)` + VS-to-FS streams as `@location` outputs).
    /// 3. Generates `@vertex fn vs_main(input: VertexInput) -> VertexOutput { ... }`.
    pub fn generate_vertex_entry(
        &self,
        router: &StreamRouter,
        entry: &EntryPointDef,
        _bindings: &[ShaderBinding],
    ) -> ShaderResult<String> {
        let vs_input = router.generate_vs_input_struct("VertexInput");
        let vs_output = router.generate_vs_output_struct("VertexOutput");

        // Build function body.
        let mut body_lines = Vec::new();
        body_lines.push("var output: VertexOutput;".to_string());

        for (name, ty, init) in &entry.local_vars {
            match init {
                Some(v) => body_lines.push(format!("var {}: {} = {};", name, ty.to_wgsl(), v)),
                None => body_lines.push(format!("var {}: {};", name, ty.to_wgsl())),
            }
        }

        if !entry.body.is_empty() {
            body_lines.push(entry.body.source.clone());
        }

        body_lines.push("return output;".to_string());

        let body_str = body_lines.join("\n");
        let indented = WgslFragment::new(&body_str).indent(4);

        Ok(format!(
            "{}\n{}\n@vertex\nfn {}(input: VertexInput) -> VertexOutput {{\n{}\n}}\n",
            vs_input, vs_output, entry.name, indented
        ))
    }

    /// Generate the fragment entry point function with proper I/O.
    ///
    /// 1. Generates `FragmentInput` struct (matches VertexOutput).
    /// 2. Generates `@fragment fn fs_main(input: FragmentInput) -> @location(0) vec4<f32> { ... }`.
    pub fn generate_fragment_entry(
        &self,
        router: &StreamRouter,
        entry: &EntryPointDef,
        _bindings: &[ShaderBinding],
    ) -> ShaderResult<String> {
        let fs_input = router.generate_fs_input_struct("FragmentInput");

        let mut body_lines = Vec::new();

        for (name, ty, init) in &entry.local_vars {
            match init {
                Some(v) => body_lines.push(format!("var {}: {} = {};", name, ty.to_wgsl(), v)),
                None => body_lines.push(format!("var {}: {};", name, ty.to_wgsl())),
            }
        }

        if !entry.body.is_empty() {
            body_lines.push(entry.body.source.clone());
        }

        let body_str = body_lines.join("\n");
        let indented = WgslFragment::new(&body_str).indent(4);

        Ok(format!(
            "{}\n@fragment\nfn {}(input: FragmentInput) -> @location(0) vec4<f32> {{\n{}\n}}\n",
            fs_input, entry.name, indented
        ))
    }

    /// Generate the compute entry point function.
    pub fn generate_compute_entry(
        &self,
        entry: &ComputeEntryPointDef,
        _bindings: &[ShaderBinding],
    ) -> ShaderResult<String> {
        let mut body_lines = Vec::new();

        for (name, ty, init) in &entry.local_vars {
            match init {
                Some(v) => body_lines.push(format!("var {}: {} = {};", name, ty.to_wgsl(), v)),
                None => body_lines.push(format!("var {}: {};", name, ty.to_wgsl())),
            }
        }

        if !entry.body.is_empty() {
            body_lines.push(entry.body.source.clone());
        }

        let body_str = body_lines.join("\n");
        let indented = WgslFragment::new(&body_str).indent(4);

        let [x, y, z] = entry.workgroup_size;

        Ok(format!(
            "@compute @workgroup_size({}, {}, {})\nfn {}(@builtin(global_invocation_id) global_id: vec3<u32>) {{\n{}\n}}\n",
            x, y, z, entry.name, indented
        ))
    }

    /// Validate the composed shader before generation.
    pub fn validate(&self, shader: &ComposedShader) -> ShaderResult<()> {
        // At least one entry point.
        let has_graphics = shader.vertex_entry.is_some() && shader.fragment_entry.is_some();
        let has_compute = shader.compute_entry.is_some();
        if !has_graphics && !has_compute {
            return Err(ShaderError::Composition {
                message: "Shader must have at least one entry point \
                          (vertex+fragment OR compute)"
                    .into(),
            });
        }
        if has_compute && (has_graphics || shader.vertex_entry.is_some() || shader.fragment_entry.is_some()) {
            return Err(ShaderError::Composition {
                message: "Shader cannot have both compute and graphics entry points".into(),
            });
        }

        // Binding conflicts.
        let mut binding_map: HashMap<(u32, u32), &str> = HashMap::new();
        for b in &shader.bindings {
            if let Some(existing) = binding_map.get(&(b.group, b.binding)) {
                if *existing != b.name.as_str() {
                    return Err(ShaderError::BindingConflict {
                        group: b.group,
                        binding: b.binding,
                        existing: existing.to_string(),
                        new: b.name.clone(),
                    });
                }
            } else {
                binding_map.insert((b.group, b.binding), &b.name);
            }
        }

        // Stream router validation.
        shader.streams.validate()?;

        // Entry point body not empty.
        if let Some(ref entry) = shader.vertex_entry {
            if entry.body.is_empty() && entry.local_vars.is_empty() {
                return Err(ShaderError::Composition {
                    message: "Vertex entry point body is empty".into(),
                });
            }
        }
        if let Some(ref entry) = shader.fragment_entry {
            if entry.body.is_empty() && entry.local_vars.is_empty() {
                return Err(ShaderError::Composition {
                    message: "Fragment entry point body is empty".into(),
                });
            }
        }
        if let Some(ref entry) = shader.compute_entry {
            if entry.body.is_empty() && entry.local_vars.is_empty() {
                return Err(ShaderError::Composition {
                    message: "Compute entry point body is empty".into(),
                });
            }
        }

        // Referenced struct types must be defined.
        let defined: std::collections::HashSet<&str> =
            shader.structs.iter().map(|s| s.name.as_str()).collect();
        for b in &shader.bindings {
            match &b.resource_type {
                BindingResourceType::UniformBuffer | BindingResourceType::StorageBuffer { .. } => {
                    let struct_name = buffer_struct_name(&b.name);
                    if !defined.contains(struct_name.as_str()) {
                        return Err(ShaderError::Composition {
                            message: format!(
                                "Binding '{}' references struct '{}' which is not defined",
                                b.name, struct_name
                            ),
                        });
                    }
                }
                _ => {}
            }
        }

        Ok(())
    }

    /// Generate WGSL and validate it with naga's WGSL parser.
    pub fn generate_and_validate(&self, shader: &ComposedShader) -> ShaderResult<String> {
        let wgsl = self.generate(shader)?;
        match naga::front::wgsl::parse_str(&wgsl) {
            Ok(_module) => Ok(wgsl),
            Err(e) => Err(ShaderError::WgslValidation {
                message: format!("{}", e),
            }),
        }
    }

    fn generate_global_vars(&self, vars: &[GlobalVarDef]) -> String {
        generate_global_vars_section(vars)
    }
}

impl Default for WgslGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Global variable generation helper.
fn generate_global_vars_section(vars: &[GlobalVarDef]) -> String {
    vars.iter()
        .map(|v| {
            let init = match &v.init {
                Some(i) => format!(" = {}", i),
                None => String::new(),
            };
            format!(
                "var<{}> {}: {}{};",
                v.address_space.to_wgsl(),
                v.name,
                v.ty.to_wgsl(),
                init
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Derive the conventional struct name for a buffer binding (matching `ShaderBinding::struct_name_for_buffer`).
fn buffer_struct_name(binding_name: &str) -> String {
    let mut s = binding_name.to_string();
    if let Some(first) = s.get_mut(0..1) {
        first.make_ascii_uppercase();
    }
    format!("{}Data", s)
}

// ─── Builder ─────────────────────────────────────────────────────────────────

/// Builder for constructing [`ComposedShader`] instances.
#[derive(Debug, Clone)]
pub struct ComposedShaderBuilder {
    name: String,
    streams: StreamRouter,
    bindings: Vec<ShaderBinding>,
    structs: Vec<StructDef>,
    functions: Vec<FunctionDef>,
    vertex_entry: Option<EntryPointDef>,
    fragment_entry: Option<EntryPointDef>,
    compute_entry: Option<ComputeEntryPointDef>,
    constants: Vec<ConstantDef>,
    global_vars: Vec<GlobalVarDef>,
}

impl ComposedShaderBuilder {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            streams: StreamRouter::new(),
            bindings: Vec::new(),
            structs: Vec::new(),
            functions: Vec::new(),
            vertex_entry: None,
            fragment_entry: None,
            compute_entry: None,
            constants: Vec::new(),
            global_vars: Vec::new(),
        }
    }

    pub fn add_stream(&mut self, decl: StreamDeclaration) -> ShaderResult<&mut Self> {
        self.streams.add_stream(decl)?;
        Ok(self)
    }

    pub fn add_streams(&mut self, decls: Vec<StreamDeclaration>) -> ShaderResult<&mut Self> {
        self.streams.add_streams(decls)?;
        Ok(self)
    }

    pub fn add_binding(&mut self, binding: ShaderBinding) -> &mut Self {
        self.bindings.push(binding);
        self
    }

    pub fn add_struct(&mut self, s: StructDef) -> &mut Self {
        self.structs.push(s);
        self
    }

    pub fn add_function(&mut self, f: FunctionDef) -> &mut Self {
        self.functions.push(f);
        self
    }

    pub fn vertex_entry(&mut self, name: impl Into<String>, body: WgslFragment) -> &mut Self {
        self.vertex_entry = Some(EntryPointDef {
            name: name.into(),
            body,
            local_vars: Vec::new(),
        });
        self
    }

    pub fn fragment_entry(&mut self, name: impl Into<String>, body: WgslFragment) -> &mut Self {
        self.fragment_entry = Some(EntryPointDef {
            name: name.into(),
            body,
            local_vars: Vec::new(),
        });
        self
    }

    pub fn compute_entry(
        &mut self,
        name: impl Into<String>,
        workgroup_size: [u32; 3],
        body: WgslFragment,
    ) -> &mut Self {
        self.compute_entry = Some(ComputeEntryPointDef {
            name: name.into(),
            workgroup_size,
            body,
            local_vars: Vec::new(),
        });
        self
    }

    pub fn add_constant(&mut self, c: ConstantDef) -> &mut Self {
        self.constants.push(c);
        self
    }

    pub fn add_global_var(&mut self, v: GlobalVarDef) -> &mut Self {
        self.global_vars.push(v);
        self
    }

    pub fn build(self) -> ComposedShader {
        ComposedShader {
            name: self.name,
            streams: self.streams,
            bindings: self.bindings,
            structs: self.structs,
            functions: self.functions,
            vertex_entry: self.vertex_entry,
            fragment_entry: self.fragment_entry,
            compute_entry: self.compute_entry,
            constants: self.constants,
            global_vars: self.global_vars,
        }
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stream::presets;

    /// Build a minimal valid vertex+fragment shader for testing.
    fn build_simple_shader() -> ComposedShader {
        let mut builder = ComposedShaderBuilder::new("test_shader");
        builder.add_stream(presets::position()).unwrap();
        builder.add_stream(presets::normal()).unwrap();
        builder.vertex_entry(
            "vs_main",
            WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"),
        );
        builder.fragment_entry(
            "fs_main",
            WgslFragment::new("return vec4<f32>(1.0, 0.0, 0.0, 1.0);"),
        );
        builder.build()
    }

    #[test]
    fn test_generate_simple_vertex_fragment() {
        let shader = build_simple_shader();
        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();

        assert!(wgsl.contains("struct VertexInput {"));
        assert!(wgsl.contains("struct VertexOutput {"));
        assert!(wgsl.contains("@vertex"));
        assert!(wgsl.contains("fn vs_main(input: VertexInput) -> VertexOutput"));
        assert!(wgsl.contains("struct FragmentInput {"));
        assert!(wgsl.contains("@fragment"));
        assert!(wgsl.contains("fn fs_main(input: FragmentInput) -> @location(0) vec4<f32>"));
        assert!(wgsl.contains("@builtin(position) clip_position: vec4<f32>"));
        assert!(wgsl.contains("@location(0) position: vec3<f32>"));
        assert!(wgsl.contains("@location(1) normal: vec3<f32>"));
    }

    #[test]
    fn test_generate_with_bindings() {
        let mut builder = ComposedShaderBuilder::new("binding_test");
        builder.add_stream(presets::position()).unwrap();
        builder.vertex_entry("vs_main", WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"));
        builder.fragment_entry("fs_main", WgslFragment::new("return vec4<f32>(1.0);"));
        builder.add_binding(ShaderBinding {
            group: 0,
            binding: 0,
            name: "albedo_tex".into(),
            resource_type: BindingResourceType::Texture {
                dimension: TextureDimension::D2,
                sample_type: TextureSampleType::Float,
            },
            visibility: wgpu::ShaderStages::FRAGMENT,
        });
        builder.add_binding(ShaderBinding {
            group: 0,
            binding: 1,
            name: "tex_sampler".into(),
            resource_type: BindingResourceType::Sampler(SamplerType::Filtering),
            visibility: wgpu::ShaderStages::FRAGMENT,
        });
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("@group(0) @binding(0) var albedo_tex: texture_2d<f32>;"));
        assert!(wgsl.contains("@group(0) @binding(1) var tex_sampler: sampler;"));
    }

    #[test]
    fn test_generate_compute_shader() {
        let mut builder = ComposedShaderBuilder::new("compute_test");
        builder.compute_entry(
            "cs_main",
            [64, 1, 1],
            WgslFragment::new("let idx = global_id.x;"),
        );
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("@compute @workgroup_size(64, 1, 1)"));
        assert!(wgsl.contains("fn cs_main(@builtin(global_invocation_id) global_id: vec3<u32>)"));
        assert!(wgsl.contains("let idx = global_id.x;"));
    }

    #[test]
    fn test_binding_conflict_detection() {
        let generator = WgslGenerator::new();
        let bindings = vec![
            ShaderBinding {
                group: 0,
                binding: 0,
                name: "tex_a".into(),
                resource_type: BindingResourceType::Texture {
                    dimension: TextureDimension::D2,
                    sample_type: TextureSampleType::Float,
                },
                visibility: wgpu::ShaderStages::FRAGMENT,
            },
            ShaderBinding {
                group: 0,
                binding: 0,
                name: "tex_b".into(),
                resource_type: BindingResourceType::Texture {
                    dimension: TextureDimension::D2,
                    sample_type: TextureSampleType::Float,
                },
                visibility: wgpu::ShaderStages::FRAGMENT,
            },
        ];
        let result = generator.generate_bindings(&bindings);
        assert!(result.is_err());
        match result.unwrap_err() {
            ShaderError::BindingConflict { group, binding, existing, new } => {
                assert_eq!(group, 0);
                assert_eq!(binding, 0);
                assert_eq!(existing, "tex_a");
                assert_eq!(new, "tex_b");
            }
            other => panic!("Expected BindingConflict, got: {:?}", other),
        }
    }

    #[test]
    fn test_generate_with_functions() {
        let mut builder = ComposedShaderBuilder::new("func_test");
        builder.add_stream(presets::position()).unwrap();
        builder.add_function(FunctionDef {
            name: "helper_func".into(),
            parameters: vec![("x".into(), WgslType::F32)],
            return_type: Some(WgslType::F32),
            body: WgslFragment::new("return x * 2.0;"),
            overridable: false,
        });
        builder.vertex_entry("vs_main", WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"));
        builder.fragment_entry("fs_main", WgslFragment::new("return vec4<f32>(1.0);"));
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("fn helper_func(x: f32) -> f32"));

        // Helper function must appear before entry points.
        let helper_pos = wgsl.find("fn helper_func").unwrap();
        let vs_pos = wgsl.find("@vertex").unwrap();
        assert!(helper_pos < vs_pos);
    }

    #[test]
    fn test_generate_with_constants() {
        let mut builder = ComposedShaderBuilder::new("const_test");
        builder.add_constant(ConstantDef {
            name: "roughness_override".into(),
            ty: WgslType::F32,
            id: 0,
            default_value: Some("0.5".into()),
        });
        builder.add_constant(ConstantDef {
            name: "max_lights".into(),
            ty: WgslType::U32,
            id: 1,
            default_value: Some("16u".into()),
        });
        builder.compute_entry("cs_main", [1, 1, 1], WgslFragment::new("let x = 0u;"));
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("override @id(0) roughness_override: f32 = 0.5;"));
        assert!(wgsl.contains("override @id(1) max_lights: u32 = 16u;"));
    }

    #[test]
    fn test_naga_validation_success() {
        let shader = build_simple_shader();
        let generator = WgslGenerator::new();
        let result = generator.generate_and_validate(&shader);
        assert!(result.is_ok(), "Naga validation failed: {:?}", result.err());
    }

    #[test]
    fn test_vertex_fragment_io_matching() {
        let shader = build_simple_shader();
        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();

        // Both structs must have the same location fields.
        assert!(wgsl.contains("struct VertexOutput {"));
        assert!(wgsl.contains("struct FragmentInput {"));
        for i in 0..2 {
            let loc_field = format!("@location({})", i);
            // Each location field should appear at least twice (once in VS output, once in FS input).
            let count = wgsl.matches(&loc_field).count();
            assert!(
                count >= 2,
                "Location {} appears {} times, expected >= 2",
                i,
                count
            );
        }
    }

    #[test]
    fn test_validate_no_entry_point() {
        let shader = ComposedShaderBuilder::new("empty").build();
        let generator = WgslGenerator::new();
        let result = generator.validate(&shader);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_empty_body() {
        let mut builder = ComposedShaderBuilder::new("empty_body");
        builder.add_stream(presets::position()).unwrap();
        builder.vertex_entry("vs_main", WgslFragment::empty());
        builder.fragment_entry("fs_main", WgslFragment::empty());
        let shader = builder.build();
        let generator = WgslGenerator::new();
        assert!(generator.validate(&shader).is_err());
    }

    #[test]
    fn test_builder_api() {
        let mut builder = ComposedShaderBuilder::new("builder_test");
        builder.add_stream(presets::position()).unwrap();
        builder.add_stream(presets::normal()).unwrap();
        builder.add_stream(presets::uv(0)).unwrap();
        builder.vertex_entry("vs_main", WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"));
        builder.fragment_entry("fs_main", WgslFragment::new("return vec4<f32>(1.0);"));
        let shader = builder.build();
        assert_eq!(shader.name, "builder_test");
        assert!(shader.vertex_entry.is_some());
        assert!(shader.fragment_entry.is_some());
        assert!(shader.compute_entry.is_none());
        assert_eq!(shader.streams.streams().len(), 3);
    }

    #[test]
    fn test_generate_global_vars() {
        let mut builder = ComposedShaderBuilder::new("globals_test");
        builder.add_global_var(GlobalVarDef {
            name: "temp_data".into(),
            ty: WgslType::Vec4(WgslScalarType::F32),
            address_space: AddressSpace::Private,
            init: Some("vec4<f32>(0.0)".into()),
        });
        builder.compute_entry("cs_main", [1, 1, 1], WgslFragment::new("let x = temp_data;"));
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("var<private> temp_data: vec4<f32> = vec4<f32>(0.0);"));
    }

    #[test]
    fn test_address_space_wgsl() {
        assert_eq!(AddressSpace::Private.to_wgsl(), "private");
        assert_eq!(AddressSpace::Workgroup.to_wgsl(), "workgroup");
    }

    #[test]
    fn test_binding_sorting() {
        let generator = WgslGenerator::new();
        let bindings = vec![
            ShaderBinding {
                group: 1,
                binding: 0,
                name: "tex_b".into(),
                resource_type: BindingResourceType::Texture {
                    dimension: TextureDimension::D2,
                    sample_type: TextureSampleType::Float,
                },
                visibility: wgpu::ShaderStages::FRAGMENT,
            },
            ShaderBinding {
                group: 0,
                binding: 0,
                name: "tex_a".into(),
                resource_type: BindingResourceType::Texture {
                    dimension: TextureDimension::D2,
                    sample_type: TextureSampleType::Float,
                },
                visibility: wgpu::ShaderStages::FRAGMENT,
            },
        ];
        let result = generator.generate_bindings(&bindings).unwrap();
        let a_pos = result.find("tex_a").unwrap();
        let b_pos = result.find("tex_b").unwrap();
        assert!(a_pos < b_pos, "Bindings should be sorted by (group, binding)");
    }

    #[test]
    fn test_naga_validation_compute() {
        let mut builder = ComposedShaderBuilder::new("compute_valid");
        builder.compute_entry(
            "cs_main",
            [8, 8, 1],
            WgslFragment::new("let idx = global_id.x;"),
        );
        let shader = builder.build();
        let generator = WgslGenerator::new();
        let result = generator.generate_and_validate(&shader);
        assert!(result.is_ok(), "Naga validation failed: {:?}", result.err());
    }

    #[test]
    fn test_naga_validation_with_texture_bindings() {
        let mut builder = ComposedShaderBuilder::new("tex_shader");
        builder.add_stream(presets::position()).unwrap();
        builder.add_binding(ShaderBinding {
            group: 0,
            binding: 0,
            name: "my_tex".into(),
            resource_type: BindingResourceType::Texture {
                dimension: TextureDimension::D2,
                sample_type: TextureSampleType::Float,
            },
            visibility: wgpu::ShaderStages::FRAGMENT,
        });
        builder.add_binding(ShaderBinding {
            group: 0,
            binding: 1,
            name: "my_sampler".into(),
            resource_type: BindingResourceType::Sampler(SamplerType::Filtering),
            visibility: wgpu::ShaderStages::FRAGMENT,
        });
        builder.vertex_entry(
            "vs_main",
            WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"),
        );
        builder.fragment_entry(
            "fs_main",
            WgslFragment::new("return textureSample(my_tex, my_sampler, vec2<f32>(0.5));"),
        );
        let shader = builder.build();
        let generator = WgslGenerator::new();
        let result = generator.generate_and_validate(&shader);
        assert!(result.is_ok(), "Naga validation failed: {:?}", result.err());
    }

    #[test]
    fn test_generate_structs_section() {
        let generator = WgslGenerator::new();
        let structs = vec![
            StructDef {
                name: "Camera".into(),
                fields: vec![
                    StructField {
                        name: "view_projection".into(),
                        ty: WgslType::Mat4x4(WgslScalarType::F32),
                        attributes: vec![],
                    },
                    StructField {
                        name: "camera_position".into(),
                        ty: WgslType::Vec4(WgslScalarType::F32),
                        attributes: vec![],
                    },
                ],
            },
            StructDef {
                name: "Material".into(),
                fields: vec![StructField {
                    name: "base_color".into(),
                    ty: WgslType::Vec4(WgslScalarType::F32),
                    attributes: vec![],
                }],
            },
        ];
        let wgsl = generator.generate_structs(&structs);
        assert!(wgsl.contains("struct Camera {"));
        assert!(wgsl.contains("struct Material {"));
        assert!(wgsl.contains("view_projection: mat4x4<f32>"));
    }

    #[test]
    fn test_generate_with_local_vars() {
        let mut builder = ComposedShaderBuilder::new("local_vars_test");
        builder.add_stream(presets::position()).unwrap();

        let vs_entry = EntryPointDef {
            name: "vs_main".into(),
            body: WgslFragment::new("output.clip_position = scaled_pos;"),
            local_vars: vec![
                (
                    "scale".to_string(),
                    WgslType::F32,
                    Some("2.0".to_string()),
                ),
                (
                    "scaled_pos".to_string(),
                    WgslType::Vec4(WgslScalarType::F32),
                    Some("vec4<f32>(input.position * scale, 1.0)".to_string()),
                ),
            ],
        };
        builder.vertex_entry = Some(vs_entry);

        builder.fragment_entry("fs_main", WgslFragment::new("return vec4<f32>(1.0);"));
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.contains("var scale: f32 = 2.0;"));
        assert!(wgsl.contains("var scaled_pos: vec4<f32> = vec4<f32>(input.position * scale, 1.0);"));
    }

    #[test]
    fn test_buffer_struct_name() {
        assert_eq!(buffer_struct_name("camera"), "CameraData");
        assert_eq!(buffer_struct_name("material"), "MaterialData");
        assert_eq!(buffer_struct_name("Object"), "ObjectData");
    }

    #[test]
    fn test_constant_no_default() {
        let generator = WgslGenerator::new();
        let constants = vec![ConstantDef {
            name: "threshold".into(),
            ty: WgslType::F32,
            id: 5,
            default_value: None,
        }];
        let wgsl = generator.generate_constants(&constants);
        assert_eq!(wgsl, "override @id(5) threshold: f32;");
    }

    #[test]
    fn test_generate_functions_section() {
        let generator = WgslGenerator::new();
        let functions = vec![
            FunctionDef {
                name: "add".into(),
                parameters: vec![
                    ("a".into(), WgslType::F32),
                    ("b".into(), WgslType::F32),
                ],
                return_type: Some(WgslType::F32),
                body: WgslFragment::new("return a + b;"),
                overridable: false,
            },
            FunctionDef {
                name: "mul".into(),
                parameters: vec![
                    ("a".into(), WgslType::F32),
                    ("b".into(), WgslType::F32),
                ],
                return_type: Some(WgslType::F32),
                body: WgslFragment::new("return a * b;"),
                overridable: true,
            },
        ];
        let wgsl = generator.generate_functions(&functions);
        assert!(wgsl.contains("fn add(a: f32, b: f32) -> f32"));
        assert!(wgsl.contains("fn mul(a: f32, b: f32) -> f32"));
    }

    #[test]
    fn test_header_comment() {
        let shader = build_simple_shader();
        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();
        assert!(wgsl.starts_with("// Generated by shader_framework — test_shader"));
    }

    #[test]
    fn test_output_order() {
        let mut builder = ComposedShaderBuilder::new("order_test");
        builder.add_stream(presets::position()).unwrap();
        builder.add_constant(ConstantDef {
            name: "k".into(),
            ty: WgslType::F32,
            id: 0,
            default_value: Some("1.0".into()),
        });
        builder.add_struct(StructDef {
            name: "MyStruct".into(),
            fields: vec![StructField {
                name: "value".into(),
                ty: WgslType::F32,
                attributes: vec![],
            }],
        });
        builder.add_function(FunctionDef {
            name: "helper".into(),
            parameters: vec![],
            return_type: None,
            body: WgslFragment::new("let x = 1.0;"),
            overridable: false,
        });
        builder.vertex_entry("vs_main", WgslFragment::new("output.clip_position = vec4<f32>(input.position, 1.0);"));
        builder.fragment_entry("fs_main", WgslFragment::new("return vec4<f32>(1.0);"));
        let shader = builder.build();

        let generator = WgslGenerator::new();
        let wgsl = generator.generate(&shader).unwrap();

        let header_pos = wgsl.find("// Generated").unwrap();
        let const_pos = wgsl.find("override").unwrap();
        let struct_pos = wgsl.find("struct MyStruct").unwrap();
        let func_pos = wgsl.find("fn helper").unwrap();
        let vs_pos = wgsl.find("@vertex").unwrap();
        let fs_pos = wgsl.find("@fragment").unwrap();

        assert!(header_pos < const_pos);
        assert!(const_pos < struct_pos);
        assert!(struct_pos < func_pos);
        assert!(func_pos < vs_pos);
        assert!(vs_pos < fs_pos);
    }

    #[test]
    fn test_default_impl() {
        let generator = WgslGenerator::default();
        let shader = build_simple_shader();
        assert!(generator.generate(&shader).is_ok());
    }
}
